services:
  bot:
    build: .
    volumes:
      - ./config.json:/app/config.json
      - ./data:/app/data
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "node", "-e", "fetch('http://localhost:8080/health').then(r => r.json()).then(data => process.exit(data.status === 'healthy' ? 0 : 1))"]
      interval: 30s
      timeout: 10s
      retries: 3 